# Generated by Django 5.0.7 on 2024-08-07 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_profile',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='admin_profile',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
