# Generated by Django 5.0.7 on 2024-08-07 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_qc_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='my_Qc_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qc_file', models.FileField(upload_to='qc')),
                ('from_date', models.CharField(max_length=100, null=True)),
                ('to_date', models.CharField(max_length=100, null=True)),
                ('start', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now=True)),
                ('end', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
                ('my_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.my_upload_file')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.qc_user')),
            ],
        ),
    ]
