# Generated by Django 5.0.7 on 2024-08-10 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_ed_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Editor_push',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_length', models.IntegerField()),
                ('date', models.DateField(auto_now=True)),
                ('sta', models.BooleanField(default=False)),
                ('Editior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.ed_user')),
                ('qc_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.my_qc_data')),
                ('qc_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.qc_user')),
            ],
        ),
    ]
