# Generated by Django 5.0.7 on 2024-08-11 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_editor_push'),
    ]

    operations = [
        migrations.CreateModel(
            name='ED_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('contact', models.CharField(max_length=100, null=True)),
                ('dob', models.DateField(null=True)),
                ('dig', models.CharField(max_length=100, null=True)),
                ('img', models.ImageField(default='App/static/image/user.png', upload_to='profile')),
                ('gender', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.ed_user')),
            ],
        ),
    ]
