# Generated by Django 5.0.7 on 2024-08-11 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_ed_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Final_data_PM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('Edited_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.editor_push')),
                ('Editior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.ed_user')),
            ],
        ),
    ]
