# Generated by Django 5.0.7 on 2024-08-13 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_final_data_pm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doubt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sr_no', models.CharField(max_length=100)),
                ('msg', models.CharField(max_length=2000)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.my_qc_data')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.qc_user')),
            ],
        ),
    ]
