# Generated by Django 5.0.7 on 2024-08-25 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_doubt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ed_profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='qc_profile',
            name='user',
        ),
        migrations.AddField(
            model_name='my_upload_file',
            name='o_len',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Admin_profile',
        ),
        migrations.DeleteModel(
            name='ED_profile',
        ),
        migrations.DeleteModel(
            name='QC_profile',
        ),
    ]
